### ISSUE TITLE
Suggestion: Add a peepToggle command

### ISSUE THREAD

**Issue by JamesMessinger** [natewallace/peep#1]
You've defined two commands: `extension.peepAll` and `extension.peepNone`.   It would be great if you could also define an `extension.peepToggle` command, which would simply toggle the setting between true and false.  This is especially handy because it can be bound to a keyboard shortcut to easily show/hide excluded files.

**Comment by natewallace** [comment]
Good suggestion.  I've pushed version 0.0.2 to the marketplace with a new Peep Toggle command that behaves as you've described.  Thanks!

**Comment by JamesMessinger** [comment]
Wow!  That was **insanely fast**.  Thanks !!!
