### ISSUE TITLE
Suggestion: Use JSON5.parse() instead of JSON.parse()

### ISSUE THREAD

**Issue by JamesMessinger** [natewallace/peep#2]
The code currently uses `JSON.parse()` to read the settings file, so it throws an error if the file contains comments.  The default `settings.json` file that is generated by VSCode has comments in it, which crashes Peep.

I recommend using [JSON5](https://www.npmjs.com/package/json5), which gives you a `.parse()` function that supports comments, and other "technically invalid" JSON syntax, such as trailing commas and unquoted strings.  Or you could use [strip-json-comments](https://www.npmjs.com/package/strip-json-comments), which simply removes comments from JSON, but doesn't handle the other things that JSON5 handles.

Of course, you'd still use `JSON.stringify()` when saving the file, so the comments will still be lost.  But at least the code will still work and won't throw an error.

**Comment by natewallace** [comment]
Thanks for reporting the issue.  I took a quick look at json5 and it appears the comments get stripped out when you read in the settings.json file with the parse function and then write it back out with the stringify function.  I'll have to investigate further if there is a way to preserve everything in the file after an update.

**Comment by JamesMessinger** [comment]
The only way I know of to preserve the comments would be to use an AST parser.  But that's a _lot_ more complex.  I wonder if VSCode exposes their AST, in which case, you could just use theirs.

If the AST thing ends up being too complicated, then JSON5 is at least better than nothing.  The comments will still be lost, but at least the command will succeed.

**Comment by natewallace** [comment]
I found a package that will parse json with comments and preserve them when writing back to file with stringify: [comment-json](https://www.npmjs.com/package/comment-json).

I've update the code to use this package and published version 0.0.3 to the marketplace with the change.  Thanks for your help.

**Comment by JamesMessinger** [comment]
oh badass!  good find.  I may use that package on some of my own projects.
