### ISSUE TITLE
Consider using the WorkspaceConfguration API

### ISSUE THREAD

**Issue by schmuli** [natewallace/peep#4]
Now that there is an API for accessing the active configuration, without having to read and write files, this can make this extension much faster.

http://code.visualstudio.com/docs/extensionAPI/vscode-api - Search for `getConfiguration`.

You can also see the API in the TS definition file: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3866

Thanks for a great extension.

**Comment by natewallace** [comment]
Unfortunatley I've been locked out of the account used to publish this extension.  In order to update this extension I would need to publish it as an entirely new extension which I'm not planning on doing at this time.

**Comment by schmuli** [comment]
I'm sorry to hear about you being locked out, especially as this affects your future work. Is there no way to fix this?

**Comment by natewallace** [comment]
@Sidneys1 is working on a fork of this extension that he plans to publish.  Perhaps you could collaborate with him.
